### ISSUE TITLE
how testing this prover? 

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [flijnzaad/natural-natural-deduction#1]
Hello, this prover seems very nice, but I am unable to understand how testing it. Where have I to write formulas to test their validity? It is very unclear and th documentation should be more explicit about this basic point. Thanks.

**Comment by m4lvin** [comment]
Hi :wave: 

Admittedly there is little explanation in the readme at the moment. You might want to have a look at the [related BSc thesis](https://fse.studenttheses.ub.rug.nl/25522/1/bAI_2021_LijnzaadFJA.pdf).

The formulas to be checked have to be given in the file [`queries.pl`](https://github.com/flijnzaad/natural-natural-deduction/blob/main/queries.pl).

For example, to get a proof for the first query (where given `and(p, q)` the system has to prove `or(p,q)`), do this:

```
$ git clone https://github.com/flijnzaad/natural-natural-deduction.git
$ cd natural-natural-deduction/
$ swipl system.pl queries.pl
?- q1(X).
X = [line(1, and(p, q), premise, 0), line(2, p, conjElim, 1), line(3, or(p, q), disjIntro, 2)].
```

If you want nicer LaTeX output etc., then go into the `interface` folder and run `main.py` there:

```
$ cd interface
$ pip install --user pyswip
$ ./main.py --help
Usage: 
    1) ./main.py               Solve the last example query; produce a tex
                               file including preamble and label the query;
                               compile the tex file and open the pdf
    2) ./main.py [options]     Solve queries and produce/open files according
                               to the options
    3) ./main.py --help        Display this message
    4) ./main.py --in-help     Display the input help
    5) ./main.py --version     Display the system's version
    6) ./main.py --clean       Remove all proof tex and pdf files

Options:
    -a              Solve all example queries in queries.pl
    -q i            Solve only query number i
    -r i,j          Solve queries i until and including j
    -i              Manually input premises and conclusion; see --in-help
                    for instructions and more information
    --tex           Only produce a tex file without preamble or labeled
                    queries, don't compile or open pdf
    --clip          Same as --tex, but copy the LaTeX code to the clipboard
                    instead of producing a tex file
    --cliptex       Same as --clip, but also produce the tex file
    --nolabel       Don't add labels to the queries
```

Hope this helps, @flijnzaad might have more to say of course.

**Comment by joseph-vidal-rosset** [comment]
Many thanks ! I understand now. You reply is very helpful, and the prover works smoothly ! Nice work !
